#!/bin/bash -e

version=$1
url=$2

if [ "$version" = "" ] || [ "$url" = "" ]; then
  echo "Usage: `basename $0` <VERSION> <URL>"
  echo "Downloads the binaries for a specific version of MySQL."
  echo "If the binaries already exist nothing will be downloaded"
  exit 1
fi

# create the bin-folder if necessary
if [ ! -d mysql-bin ]; then
  mkdir mysql-bin
fi

target=mysql-bin/$version

# drop out if the binaries already have been downloaded
if [ -d $target ]; then
  echo "$target already exists, nothing to download."
  exit 0
fi

# download
if [ -d $target.tmp ]; then
  rm -r $target.tmp
fi

mkdir $target.tmp

echo "Downloading $url."
wget -O $target.tmp/dist $url

# unpack
echo "Unpacking binaries."
tar --extract --directory=$target.tmp --strip-components=1 --file=$target.tmp/dist

# cleanup
rm $target.tmp/dist
mv $target.tmp $target

echo "Installed $version."
exit 0

