#!/bin/bash

alias=$1
url=$2

if [ "$alias" = "" ] || [ "$url" = "" ]; then
  echo "Usage: `basename $0` <ALIAS> <URL>"
  echo "Downloads the binaries for a version of MySQL under a provided alias."
  echo "If the binaries already exist nothing will be downloaded"
  exit 1
fi

# create the bin-folder if necessary
if [ ! -d mysql-bin ]; then
  mkdir mysql-bin
fi

target=mysql-bin/$alias

# drop out if the binaries already have been downloaded
if [ -d $target ]; then
  echo "$target already exists, nothing to download."
  exit 0
fi

# download
if [ -d $target.tmp ]; then
  rm -r $target.tmp
fi

mkdir $target.tmp

echo "Downloading $url."
curl $url > $target.tmp/binaries

# unpack

# cleanup
mv $target.tmp $target

echo "Installed $alias."
exit 0

